type AddTodo = (title: string) => void;
type DeleteTodo = (todo: Todo) => void;
type DeleteTodos = () => void;
type EditTodo = (todo: Todo) => void;
type FilterTodos = (visibiltityFilter: string) => void;
type SaveTodo = () => void;
type SearchTodos = (searchTerm: string) => void;
type ShowEdit = (todo: Todo) => void;
type ShowShearch = () => void;
type ToggleTodo = (todo: Todo) => void;
type ToggleTodos = (isAllCompleted: boolean) => void;
